Gpu eval metric
pnsemyon/catboost pull request #3
Opened 2024-04-16 21:10 UTC by pnsemyon

Before submitting a pull request, please do the following steps:

1. Read [instructions for contributors](https://catboost.ai/docs/concepts/development-and-contributions.html).
2. Make sure [the code builds](https://catboost.ai/en/docs/concepts/build-from-source).
3. If you add new functionality [add tests](https://catboost.ai/en/docs/concepts/development-and-contributions#run-tests) to check it.
4. [Run existing tests](https://catboost.ai/en/docs/concepts/development-and-contributions#run-tests) to make sure you haven't broken anything.
5. If you haven't already, sign [the Contributor License Agreement](https://yandex.ru/legal/cla/).

2024-04-20 18:15 UTC, Evgueni-Petrov-aka-espetrov requested changes

2024-04-20 18:15 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/methods/boosting_metric_calcer.h
> +                // }
нужно почистить

2024-04-20 18:15 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/gpu_metrics.cpp
> +    }
это работает только для одного гпу
это должно происходить в "ядре" типа такого https://github.com/catboost/catboost/blob/0c2e2bf9358218e005186dbb6c3ccb48029fa9af/catboost/cuda/targets/multiclass_kernels.h#L11

ядро должно внутри себя держать Descriptor и звать EvalFunc из метода Run https://github.com/catboost/catboost/blob/0c2e2bf9358218e005186dbb6c3ccb48029fa9af/catboost/cuda/targets/multiclass_kernels.h#L49

в этот метод приходят указатели на данные с учетом гпу, на которой запускается "ядро"

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov requested changes

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/user_defined.h
> +        Y_SAVELOAD_DEFINE(Targets, Weights, Predictions);
думаю, более правильно убрать Y_SAVELOAD_DEFINE и добавить проверку, что мы не в распред режиме

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/methods/boosting_metric_calcer.h
> -                // }
нужно почистить

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/libs/metrics/metric.h
> +            TConstArrayRef<float> result_weight,
snake_case -> pascalCase или вообще убрать имена

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> +            TConstArrayRef[float]  result_weight,
нужно везде убрать snake_case

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/train_lib/train.cpp
>                                                                  const TMaybe<TCustomMetricDescriptor>& evalMetricDescriptor
сборка говорит, что этот параметр теперь не используется -- давай уберем везде?

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/ut/medium/test.py
> +def test_custom_gpu_eval_metric():
тут ты просто отключил тест на цпу -- нужно вернуть task_type

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/ut/medium/test.py
> +    from numba import cuda
этот import нужно положить под if task_type == 'GPU'
...хотя, этого тут вообще не должно быть -- это должен делать питон пакет катбуста

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> +cdef extern from "catboost/cuda/targets/gpu_metrics.h":
pyx не должен зависеть от catboost/cuda, т.к. это ломает сборку питон пакета без cuda

нужно перенести TCustomGpuMetricDescriptor в catboost/libs

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> +from numba import cuda as numba_cuda
это должно быть под try, а там, где numba_cuda используется, нужно бросать exception, если модуль не загружен, или проваливаться на цпу -- ты же это делал уже?

сейчас сломаны тесты, если нет numba

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/ut/medium/test.py
> +    class RMSEMetric(object):
как у нас разделяются пользовательские эвал метрики для цпу и гпу?

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> +    # setattr(new_method, "use_optimized", True)
нужно почистить

2024-05-03 11:59 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> +def _try_cuda_jit_method(obj, method_name):
это 90% дублирует _try_jit_method -- нужно объединить

2024-05-05 03:03 UTC, pnsemyon commented on catboost/cuda/targets/user_defined.h
> +        Y_SAVELOAD_DEFINE(Targets, Weights, Predictions);
Я не очень понмиаю, что делает Y_SAVELOAD_DEFINE и зачем проверка на распределнность. Эту строчку я откуда-то скопировал

2024-05-14 05:12 UTC, Evgueni-Petrov-aka-espetrov requested changes
нужно починить сборку
хорошо, что собравшиеся тесты проходят

2024-05-14 05:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/libs/train_lib/train_model.cpp
> +        /*evalGpuMetricDescriptor*/ Nothing(),
не собирается catboost/R-package/src
catboost/R-package/src/catboostr.cpp:535:9: error: no matching function for call to 'TrainModel'
        TrainModel(
        ^~~~~~~~~~
catboost/R-package/src/catboostr.cpp:550:9: error: no matching function for call to 'TrainModel'
        TrainModel(

не собирается catboost/cuda/train_lib/ut
catboost/cuda/train_lib/ut/train_ut.cpp:86:13: error: no matching function for call to 'TrainModel'
            TrainModel(
            ^~~~~~~~~~

не собирается catboost/libs/calc_metrics/ut
catboost/libs/calc_metrics/ut/calc_metrics_ut.cpp:35:5: error: no matching function for call to 'TrainModel'
    TrainModel(
    ^~~~~~~~~~

не собирается catboost/libs/model/ut
catboost/libs/model/ut/model_summ_ut.cpp:25:5: error: no matching function for call to 'TrainModel'
    TrainModel(
    ^~~~~~~~~~

не собирается catboost/libs/model/ut/lib
catboost/libs/model/ut/lib/model_test_helpers.cpp:67:5: error: no matching function for call to 'TrainModel'
    TrainModel(
    ^~~~~~~~~~

не собирается catboost/libs/train_interface
catboost/libs/train_interface/catboost_api.cpp:210:9: error: no matching function for call to 'TrainModel'
        TrainModel(plainJsonParams,
        ^~~~~~~~~~

не собирается catboost/libs/train_lib/ut
catboost/libs/train_lib/ut/train_model_ut.cpp:122:13: error: no matching function for call to 'TrainModel'
            TrainModel(
            ^~~~~~~~~~

не собирается catboost/private/libs/algo/ut
catboost/private/libs/algo/ut/train_ut.cpp:97:9: error: no matching function for call to 'TrainModel'
        TrainModel(
        ^~~~~~~~~~

2024-05-14 05:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/user_defined.h
> +#pragma once
не собирается catboost/cuda/targets
catboost/cuda/targets/gpu_metrics.cpp:16:10: fatal error: 'catboost/cuda/targets/user_defined.h' file not found
#include <catboost/cuda/targets/user_defined.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

could not resolve include file: catboost/cuda/targets/user_defined.h included from here: catboost/cuda/targets/gpu_metrics.cpp

2024-05-14 05:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/user_defined.h
> +        Y_SAVELOAD_DEFINE(Targets, Weights, Predictions);
save load -- сериализация и десериализация параметров ядра для запуска на удаленной машине
этот сценарий не имеет смысла для user-defined функций

2024-05-14 05:18 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/train_lib/train.cpp
>                                                                  const TMaybe<TCustomMetricDescriptor>& evalMetricDescriptor
up??

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov requested changes

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/gpu_metrics.cpp
> +        // CB_ENSURE(false, "Calling custom get final error from gpu metric!\n");
нужно почистить подобные комменты

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/gpu_metrics.cpp
> -
сохраняем исходное форматирование -- везде посмотри, пожалуйста?

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/gpu_metrics.h
> +}
в конце файла нужна пустая строка

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/user_defined.h
> +            ythrow TCatBoostException() << "Distributed training and evaluation is not supported with user defined metrics";
CB_ENSURE(false, ...);

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/user_defined.h
> +            auto result_weight_ptr = TConstArrayRef<float>(ResultsWeight.Get(), ResultsWeight.ObjectCount());
выглядит неожиданно
эти адреса в памяти гпу, а сам код -- на цпу
поэтому адресная арифметика в (например, в TArrayRef::end) приводит формально к undefined behavior
хотя... не знаю... что ты думаешь?

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/user_defined.h
> +}
нужно пустую строку

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/train_lib/train.cpp
>                                                                  const TMaybe<TCustomMetricDescriptor>& evalMetricDescriptor
мы не хотим объединить TCustomMetricDescriptor и TCustomGpuMetricDescriptor? или они сильно разные?

у нас много правок, которые просто добавляют этот параметр

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/libs/metrics/metric.h
> +        // TIsMaxOptimalFuncPtr IsMaxOptimalFunc = nullptr;
это поле должно остаться

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> +            TConstArrayRef[float]  resultWeight,
лишние пробелы

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> +        # bool_t (*IsMaxOptimalFunc)(void *customData) except * with gil
нужно вернуть

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/ut/medium/test.py
> +def test_custom_gpu_eval_metric_cpu(task_type):
это как так? :-)

2024-05-23 12:12 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/ut/medium/test.py
> +        return
нужно просто старый тест расширить на гпу -- параметр task_type как раз для того, чтобы не дублировать код тестов цпу-гпу

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov requested changes

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/gpu_metrics.cpp
> +                        }
вот такой стиль нужен
```cpp
    TMetricHolder TGpuCustomMetric::Eval(
        const TStripeBuffer<const float>& target,
        const TStripeBuffer<const float>& weights,
        const TStripeBuffer<const float>& cursor,
        TScopedCacheHolder* cache,
        ui32 stream
    ) const {
        return EvalImpl<TStripeMapping>(target, weights, cursor, cache, stream);
    }
```

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/gpu_metrics.cpp
> +    {
```cpp
double TGpuCustomMetric::GetFinalError(TMetricHolder &&metricHolder) const {
```

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/gpu_metrics.cpp
> +                                                  const TMaybe<TCustomMetricDescriptor>& evalMetricDescriptor) {
нужно либо сделать стиль как в TGpuCustomMetric::Eval, либо вообще не трогать

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/gpu_metrics.h
> +                           ui32 stream = 0) const;
стиль как у TGpuCustomMetric::Eval в *.cpp

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/gpu_metrics.h
> +                                                  const TMaybe<TCustomMetricDescriptor>& evalMetricDescriptor);
либо стиль как у TGpuCustomMetric::Eval в *.cpp, либо не меняем

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/user_defined.cpp
либо убрать, либо добавить `#include "user_defined.h"`

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/private/libs/options/check_train_options.h
> +struct TCustomGpuMetricDescriptor;
нужно удалить

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> +
нужно удалить

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> -
нужно вернуть

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> +            TConstArrayRef[float]  resultWeight,
после [float] нужно оставить один пробел

2024-05-27 06:24 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/python-package/catboost/_catboost.pyx
> +
нужно одну пустую строку

2024-05-29 02:21 UTC, merged