Gpu objective metric
pnsemyon/catboost pull request #4
Opened 2024-06-02 22:40 UTC by pnsemyon

Before submitting a pull request, please do the following steps:

1. Read [instructions for contributors](https://catboost.ai/docs/concepts/development-and-contributions.html).
2. Make sure [the code builds](https://catboost.ai/en/docs/concepts/build-from-source).
3. If you add new functionality [add tests](https://catboost.ai/en/docs/concepts/development-and-contributions#run-tests) to check it.
4. [Run existing tests](https://catboost.ai/en/docs/concepts/development-and-contributions#run-tests) to make sure you haven't broken anything.
5. If you haven't already, sign [the Contributor License Agreement](https://yandex.ru/legal/cla/).

2024-06-06 12:43 UTC, Evgueni-Petrov-aka-espetrov requested changes

2024-06-06 12:43 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/methods/doc_parallel_boosting.h
> +            if constexpr (std::is_same<TPointwiseTargetsImpl<NCudaLib::TStripeMapping>, TObjective>::value) {
нужно расцепить бустинг и таргет (убрать if) в этом месте вот так:
1. добавить параметр `const TMaybe<TCustomObjectiveDescriptor>& objectiveDescriptor` в `TPointwiseTarget`, `TQuerywiseTarget`, `TNonDiagQuerywiseTarget` 
2. в `TQuerywiseTarget`, `TNonDiagQuerywiseTarget` сделать `cb_ensure(!objectiveDescriptor.defined(), ...);`
3. убрать include

2024-06-06 12:43 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/methods/dynamic_boosting.h
> +            Y_UNUSED(objectiveDescriptor);
`cb_ensure(!objectiveDescriptor.defined(), ...);`

но можно и поддрежать -- тут подходит ровно такой же таргет, как в doc_parallel_boosting.h

2024-06-06 12:43 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/gpu_metrics.cpp
> +        if (!IsUserDefined(objectiveMetricDescription.GetLossFunction())){
как мы будем учиться без objective metric?

2024-06-06 12:43 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/targets/user_defined.h
> +            Y_UNUSED(s);
если убрать `s` вот так, то y_unused не нужен
`inline void Load(IInputStream*) {`

2024-06-06 12:43 UTC, Evgueni-Petrov-aka-espetrov commented on catboost/cuda/train_lib/train_template.h
> +        const TMaybe<TCustomObjectiveDescriptor>& objectiveDescriptor,
мы const пишем перед не const -- нужно сразу за catboostOptions

посмотри, чтобы соблюдалось там, где еще не нарушено ))

2024-06-06 13:13 UTC, pnsemyon commented on catboost/cuda/targets/gpu_metrics.cpp
> +        if (!IsUserDefined(objectiveMetricDescription.GetLossFunction())){
Но оно же почем-уто учится и работает. Я так понял смысл этого вектора в том, чтобы не дублировать подсчет стандартных метрик. Если метрика пользовательская, то мы её и так не посчитаем два раза

2024-06-06 14:36 UTC, pnsemyon commented on catboost/cuda/methods/doc_parallel_boosting.h
> +            if constexpr (std::is_same<TPointwiseTargetsImpl<NCudaLib::TStripeMapping>, TObjective>::value) {
Поправил

2024-06-06 14:37 UTC, pnsemyon commented on catboost/cuda/methods/dynamic_boosting.h
> +            Y_UNUSED(objectiveDescriptor);
Не поддерживаю

2024-06-06 14:37 UTC, pnsemyon commented on catboost/cuda/targets/user_defined.h
> +            Y_UNUSED(s);
Поправил

2024-06-06 14:37 UTC, pnsemyon commented on catboost/cuda/train_lib/train_template.h
> +        const TMaybe<TCustomObjectiveDescriptor>& objectiveDescriptor,
Везде, где не было нарушений до меня, я поправил

2024-06-14 04:52 UTC, merged

2025-02-13 12:31 UTC, dubovikmaster commented
Ребята, подскажите как это должно работать? Я написал кастомный лосс и при запуске на  GPU 
получаю ошибку `AttributeError: 'TweedieObjective' object has no attribute 'calc_ders_range_gpu'`